# Generated by Django 2.2.5 on 2020-02-05 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('member_id', models.AutoField(primary_key=True, serialize=False)),
                ('real_id', models.CharField(max_length=20)),
                ('pw', models.CharField(blank=True, max_length=20, null=True)),
                ('nick_name', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=20, null=True)),
                ('pi', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'member',
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('r_code', models.AutoField(primary_key=True, serialize=False)),
                ('r_name', models.CharField(blank=True, max_length=200, null=True)),
                ('r_kind', models.CharField(blank=True, max_length=30, null=True)),
                ('r_img', models.CharField(blank=True, max_length=200, null=True)),
                ('des', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('latitude', models.FloatField(blank=True, db_column='Latitude', null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('closetime', models.CharField(blank=True, max_length=20, null=True)),
                ('number', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'restaurant',
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.Member')),
            ],
            options={
                'db_table': 'setting',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=200, null=True)),
                ('grade', models.FloatField(blank=True, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.Member')),
                ('r_code', models.ForeignKey(blank=True, db_column='r_code', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.Restaurant')),
            ],
            options={
                'db_table': 'review',
            },
        ),
        migrations.CreateModel(
            name='Recommend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.Member')),
                ('r_code', models.ForeignKey(blank=True, db_column='r_code', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.Restaurant')),
            ],
            options={
                'db_table': 'recommend',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name', models.CharField(blank=True, max_length=200, null=True)),
                ('r_code', models.ForeignKey(blank=True, db_column='r_code', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.Restaurant')),
            ],
            options={
                'db_table': 'menu',
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_dislike', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.Member')),
                ('r_code', models.ForeignKey(blank=True, db_column='r_code', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.Restaurant')),
            ],
            options={
                'db_table': 'like',
            },
        ),
        migrations.CreateModel(
            name='Img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(blank=True, max_length=200, null=True)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('r_code', models.ForeignKey(blank=True, db_column='r_code', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.Restaurant')),
            ],
            options={
                'db_table': 'img',
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.Member')),
                ('r_code', models.ForeignKey(blank=True, db_column='r_code', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.Restaurant')),
            ],
            options={
                'db_table': 'favorite',
            },
        ),
    ]
